# Generated by Django 3.0.5 on 2020-05-03 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0007_auto_20200503_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='liked',
        ),
        migrations.AddField(
            model_name='album',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
